
DROP TABLE IF EXISTS task_schema.comments;

CREATE TABLE task_schema.comments(
id BIGINT GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1)
PRIMARY KEY ,

task_id BIGINT NOT NULL,

content TEXT NOT NULL,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT fk_task_id FOREIGN KEY(task_id)
REFERENCES task_schema.tasks(id)
ON DELETE CASCADE
ON UPDATE CASCADE,



);