DROP TABLE IF EXISTS task_schema.users CASCADE;

CREATE TABLE task_schema.users (
    id BIGINT GENERATED ALWAYS AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ) PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,


    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);